"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/longevity-genie/synergy-age-mcp

identifier: longevity-genie/synergy-age-mcp

name: Holy-BIO-MCP's SynergyAge server

description: >
  A Model Context Protocol server for the SynergyAge database, providing access to experimentally validated genetic interventions and their synergistic, antagonistic, and epistatic interactions affecting lifespan across model organisms. The server enables AI-assisted research into aging and longevity through structured database queries.

codeRepository: https://github.com/longevity-genie/synergy-age-mcp

maintainer:
  - "@type": Person
    name: Anton Kulaga
    identifier: antonkulaga
    url: https://github.com/antonkulaga
  - "@type": Person
    name: Livia Zaharia
    identifier: liviazaharia2020
    url: https://github.com/liviazaharia2020

license: https://spdx.org/licenses/MIT.html

applicationCategory: HealthApplication

keywords:
  - synergyage
  - holy-bio-mcp
  - aging
  - longevity
  - genetic interactions
  - lifespan interventions
  - model organisms
  - synergistic effects
  - antagonistic interactions
  - epistasis
  - gerontology
  - bioinformatics
  - genetics

programmingLanguage:
  - Python

featureList:
  - synergyage_db_query - Execute read-only SQL queries against the SynergyAge database with comprehensive genetic intervention data
  - synergyage_get_schema_info - Get detailed database schema information including tables, columns, and data descriptions
  - synergyage_example_queries - Get example SQL queries with patterns for common aging research questions
  - resource://db-prompt - Complete database schema documentation and usage guidelines for SynergyAge
  - resource://schema-summary - Formatted summary of database tables and their purposes in longevity research
